#!/bin/sh

# Source your custom motion configurations
. /system/sdcard/scripts/common_functions.sh

echo " MOTOR DETECTION OFF "
motion_detection off 
sleep 4

MOTORSTATE=$(motor status horizontal)
MAX_POS_X=2250

echo " MOTOR MOVE "
motor right 15
sleep 3

MOTORSTATE=$(motor status horizontal)
echo " MOTOR POS $MOTORSTATE "

if [ $MOTORSTATE -gt $MAX_POS_X ]; then
	echo " CALIBRATE "
	motor reset_pos_count 100
fi

sleep 10
motion_detection on
